const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0'), ds=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parse=s=>{let [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}; const add=(d,n)=>new Date(d.getFullYear(),d.getMonth(),d.getDate()+n);
const startWeek=d=>{let x=new Date(d),n=x.getDay();return add(x,-n)}; const uid=()=>crypto.randomUUID?.()||Date.now()+Math.random();
let state=JSON.parse(localStorage.getItem('myCalendarV1')||'null')||{calendars:[{id:'work',name:'아도라블',color:'#bfe8c9',order:1,period:'오전',capacity:5},{id:'personal',name:'개인업무',color:'#d9d9d9',order:2,period:'오후',capacity:3},{id:'family',name:'가족/개인',color:'#f6e8a6',order:3,period:'저녁',capacity:2}],events:[],fixed:[],settings:{firebaseConfig:'',syncId:'my-calendar'}};
let cursor=new Date(), view='week', remoteSave=null;
function save(){localStorage.setItem('myCalendarV1',JSON.stringify(state));remoteSave?.(state);render()}
function cals(){return [...state.calendars].sort((a,b)=>a.order-b.order)} function cal(id){return state.calendars.find(x=>x.id===id)||state.calendars[0]}
function eventsOn(date){return state.events.filter(e=>date>=e.date && date<=(e.endDate||e.date)).sort((a,b)=>(cal(a.calId)?.order||99)-(cal(b.calId)?.order||99)||(a.start||'').localeCompare(b.start||''))}
function duration(e){return Number(e.hours)||0} function fmtH(h){let m=Math.round(h*60);return m%60?`${Math.floor(m/60)}시간 ${m%60}분`:`${m/60}시간`}
function syncSelects(){let opts=cals().map(c=>`<option value='${c.id}'>${c.name}</option>`).join(''); $('#cal').innerHTML=opts;$('#fcal').innerHTML=opts;$('#fixedFilter').innerHTML=`<option value='all'>전체 캘린더</option>${opts}`}
function renderSide(){syncSelects();$('#calList').innerHTML=cals().map(c=>`<div class='calRow' data-cid='${c.id}'><i class='dot' style='background:${c.color}'></i><span class='name'>${c.name}</span><small>${c.period} · ${c.capacity}h</small></div>`).join('');$$('.calRow').forEach(x=>x.onclick=()=>openCal(x.dataset.cid));renderFixed();renderLoad()}
function renderFixed(){let f=$('#fixedFilter').value||'all', month=`${cursor.getFullYear()}-${pad(cursor.getMonth()+1)}`;$('#fixedList').innerHTML=state.fixed.filter(x=>f==='all'||x.calId===f).map(x=>{let c=cal(x.calId),used=state.events.some(e=>e.fixedId===x.id&&e.date.startsWith(month));return `<div class='fixed' draggable='true' data-fid='${x.id}' style='border-left-color:${c.color}'><b>${used?'✓ ':''}${x.name}</b><small>${c.name} · ${fmtH(x.hours)}</small></div>`}).join('')||`<div class='empty'>고정업무를 등록하세요.</div>`;$$('.fixed').forEach(x=>{x.ondragstart=e=>e.dataTransfer.setData('fixedId',x.dataset.fid);x.ondblclick=()=>openFixed(x.dataset.fid)})}
function groupHtml(date){let es=eventsOn(date), html='';for(let c of cals()){let xs=es.filter(e=>e.calId===c.id);if(!xs.length)continue;let sum=xs.reduce((s,e)=>s+duration(e),0),over=sum>c.capacity;html+=`<div class='group'><div class='groupHead' style='background:${c.color}55'><span>${c.name}</span><span class='${over?'over':'ok'}'>${fmtH(sum)} / ${fmtH(c.capacity)}</span></div>${xs.map(e=>`<div class='item ${e.done?'done':''}' data-eid='${e.id}' style='border-left-color:${c.color}'><div>${e.kind==='todo'?'☐ ':''}${e.title}</div><div class='meta'>${e.allDay?'':(e.start||'')+' '}${duration(e)?'⏱ '+fmtH(duration(e)):''}</div></div>`).join('')}</div>`}let total=es.reduce((s,e)=>s+duration(e),0);return html+`<div class='dayTotal'>총 계획 ${fmtH(total)}</div>`}
function bindItems(){ $$('.item').forEach(x=>x.onclick=e=>{e.stopPropagation();openEvent(null,x.dataset.eid)});$$('[data-dropdate]').forEach(x=>{x.ondragover=e=>e.preventDefault();x.ondrop=e=>{e.preventDefault();let id=e.dataTransfer.getData('fixedId'),f=state.fixed.find(z=>z.id===id);if(f){state.events.push({id:uid(),title:f.name,calId:f.calId,date:x.dataset.dropdate,endDate:x.dataset.dropdate,allDay:true,hours:f.hours,kind:'todo',repeat:'none',memo:f.memo||'',fixedId:f.id,done:false});save()}}})}
function renderWeek(){let s=startWeek(cursor), days=[0,1,2,3,4,5,6].map(i=>add(s,i));$('#range').textContent=`${s.getFullYear()}. ${s.getMonth()+1}. ${s.getDate()} - ${days[6].getMonth()+1}. ${days[6].getDate()}`;$('#main').className='week';$('#main').innerHTML=days.map(d=>`<div class='dayCol'><div class='dayHead ${ds(d)===ds(new Date())?'today':''}'><div>${['일','월','화','수','목','금','토'][d.getDay()]}</div><div class='dateNum'>${d.getDate()}</div></div><div class='dayBody' data-dropdate='${ds(d)}' ondblclick='window.__newEvent?.("${ds(d)}")'>${groupHtml(ds(d))}</div></div>`).join('');bindItems()}
function renderMonth(){let y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),s=startWeek(first);$('#range').textContent=`${y}년 ${m+1}월`;$('#main').className='month';$('#main').innerHTML=[...Array(42)].map((_,i)=>{let d=add(s,i),es=eventsOn(ds(d));return `<div class='cell ${d.getMonth()!==m?'other':''}' data-dropdate='${ds(d)}' ondblclick='window.__newEvent?.("${ds(d)}")'><div class='mhead'>${d.getDate()}</div>${es.map(e=>`<div class='item ${e.done?'done':''}' data-eid='${e.id}' style='border-left-color:${cal(e.calId).color}'>${e.title}</div>`).join('')}</div>`}).join('');bindItems()}
function renderDay(){let d=ds(cursor);$('#range').textContent=d;$('#main').className='daySingle';$('#main').innerHTML=`<h2>${d}</h2><div data-dropdate='${d}' ondblclick='window.__newEvent?.("${d}")'>${groupHtml(d)}</div>`;bindItems()}
function renderList(){let es=[...state.events].sort((a,b)=>a.date.localeCompare(b.date)||(cal(a.calId).order-cal(b.calId).order));$('#range').textContent='일정 목록';$('#main').className='listView';let last='';$('#main').innerHTML=es.map(e=>{let h='';if(last!==e.date){last=e.date;h=`<div class='listDate'>${e.date}</div>`}let c=cal(e.calId);return `${h}<div class='item ${e.done?'done':''}' data-eid='${e.id}' style='border-left-color:${c.color}'><b>${e.title}</b><div class='meta'>${c.name} · ${fmtH(e.hours)}</div></div>`}).join('')||'<div class=empty>등록된 일정이 없습니다.</div>';bindItems()}
function renderLoad(){let s=startWeek(cursor);$('#weekLoad').innerHTML=cals().map(c=>{let sum=state.events.filter(e=>{let d=parse(e.date);return e.calId===c.id&&d>=s&&d<add(s,7)}).reduce((a,e)=>a+duration(e),0),cap=c.capacity*7,p=Math.min(100,cap?sum/cap*100:0);return `<div class='loadLine'><b>${c.name}</b> ${fmtH(sum)}<div class='loadBar'><i style='width:${p}%'></i></div></div>`}).join('')}
function render(){renderSide();$$('.views [data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===view));({week:renderWeek,month:renderMonth,day:renderDay,list:renderList}[view])()}
function openEvent(date,id){let e=state.events.find(x=>x.id===id);$('#eventTitle').textContent=e?'일정 수정':'일정 등록';$('#eid').value=e?.id||'';$('#title').value=e?.title||'';$('#cal').value=e?.calId||cals()[0]?.id;$('#date').value=e?.date||date||ds(cursor);$('#endDate').value=e?.endDate||e?.date||date||ds(cursor);$('#allDay').checked=e?.allDay??true;$('#start').value=e?.start||'';$('#end').value=e?.end||'';$('#hours').value=e?.hours??1;$('#kind').value=e?.kind||'event';$('#repeat').value=e?.repeat||'none';$('#memo').value=e?.memo||'';$('#deleteEvent').style.visibility=e?'visible':'hidden';$('#eventDlg').showModal()}
window.__newEvent=openEvent;
$('#eventForm').onsubmit=e=>{e.preventDefault();let id=$('#eid').value,obj={id:id||uid(),title:$('#title').value,calId:$('#cal').value,date:$('#date').value,endDate:$('#endDate').value||$('#date').value,allDay:$('#allDay').checked,start:$('#start').value,end:$('#end').value,hours:Number($('#hours').value)||0,kind:$('#kind').value,repeat:$('#repeat').value,memo:$('#memo').value,done:state.events.find(x=>x.id===id)?.done||false};if(id)state.events[state.events.findIndex(x=>x.id===id)]={...state.events.find(x=>x.id===id),...obj};else state.events.push(obj);$('#eventDlg').close();save()};$('#deleteEvent').onclick=()=>{let id=$('#eid').value;if(id&&confirm('삭제할까요?')){state.events=state.events.filter(x=>x.id!==id);$('#eventDlg').close();save()}}
function openCal(id){let c=state.calendars.find(x=>x.id===id);$('#cid').value=c?.id||'';$('#cname').value=c?.name||'';$('#ccolor').value=c?.color||'#d9d9d9';$('#corder').value=c?.order||state.calendars.length+1;$('#cperiod').value=c?.period||'오전';$('#ccap').value=c?.capacity??8;$('#deleteCal').style.visibility=c?'visible':'hidden';$('#calDlg').showModal()}
$('#calForm').onsubmit=e=>{e.preventDefault();let id=$('#cid').value,obj={id:id||uid(),name:$('#cname').value,color:$('#ccolor').value,order:Number($('#corder').value),period:$('#cperiod').value,capacity:Number($('#ccap').value)};if(id)state.calendars[state.calendars.findIndex(x=>x.id===id)]=obj;else state.calendars.push(obj);$('#calDlg').close();save()};$('#deleteCal').onclick=()=>{let id=$('#cid').value;if(id&&confirm('캘린더와 포함된 일정을 모두 삭제할까요?')){state.calendars=state.calendars.filter(x=>x.id!==id);state.events=state.events.filter(x=>x.calId!==id);state.fixed=state.fixed.filter(x=>x.calId!==id);$('#calDlg').close();save()}}
function openFixed(id){let f=state.fixed.find(x=>x.id===id);$('#fid').value=f?.id||'';$('#fname').value=f?.name||'';$('#fcal').value=f?.calId||cals()[0]?.id;$('#fhours').value=f?.hours??1;$('#fmemo').value=f?.memo||'';$('#deleteFixed').style.visibility=f?'visible':'hidden';$('#fixedDlg').showModal()}
$('#fixedForm').onsubmit=e=>{e.preventDefault();let id=$('#fid').value,obj={id:id||uid(),name:$('#fname').value,calId:$('#fcal').value,hours:Number($('#fhours').value)||0,memo:$('#fmemo').value};if(id)state.fixed[state.fixed.findIndex(x=>x.id===id)]=obj;else state.fixed.push(obj);$('#fixedDlg').close();save()};$('#deleteFixed').onclick=()=>{let id=$('#fid').value;if(id){state.fixed=state.fixed.filter(x=>x.id!==id);$('#fixedDlg').close();save()}}
$('#addCal').onclick=()=>openCal();$('#addFixed').onclick=()=>openFixed();$('#fixedFilter').onchange=renderFixed;$('#prev').onclick=()=>{cursor=view==='month'?new Date(cursor.getFullYear(),cursor.getMonth()-1,1):add(cursor,view==='week'?-7:-1);render()};$('#next').onclick=()=>{cursor=view==='month'?new Date(cursor.getFullYear(),cursor.getMonth()+1,1):add(cursor,view==='week'?7:1);render()};$('#today').onclick=()=>{cursor=new Date();render()};$$('.views [data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
$('#settingsBtn').onclick=()=>{$('#fbconfig').value=state.settings.firebaseConfig||'';$('#syncId').value=state.settings.syncId||'my-calendar';$('#settingsDlg').showModal()};
$('#connectFb').onclick=async()=>{try{let cfg=JSON.parse($('#fbconfig').value),syncId=$('#syncId').value||'my-calendar';state.settings.firebaseConfig=$('#fbconfig').value;state.settings.syncId=syncId;localStorage.setItem('myCalendarV1',JSON.stringify(state));let {initializeApp}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),{getFirestore,doc,setDoc,onSnapshot}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js');let app=initializeApp(cfg),db=getFirestore(app),ref=doc(db,'calendarApps',syncId),applying=false;remoteSave=async s=>{if(applying)return;await setDoc(ref,{state:s,updatedAt:new Date().toISOString()})};onSnapshot(ref,snap=>{if(snap.exists()){applying=true;state=snap.data().state;localStorage.setItem('myCalendarV1',JSON.stringify(state));render();applying=false}else remoteSave(state)});$('#syncState').textContent='Firebase 연결됨';}catch(e){$('#syncState').textContent='연결 실패: '+e.message}}
render();
